version: '3.8'

networks:
  multifinance_app_network:
    driver: bridge

services:
  db:
    image: mysql:latest
    container_name: local-mysql-multifinance-apps
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-multifinance}
      MYSQL_USER: ${MYSQL_USER:-root}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin", "ping", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - multifinance_app_network
  
  redis:
    image: redis:latest
    container_name: local-redis-multifinance-apps
    ports:
      - "6399:6379"
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}"]
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-password}
    volumes:
      - ./redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - multifinance_app_network

  app:
    image: ikhsanhilmi/multifinance-app-service:latest 
    container_name: local-multifinance-app-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
      - "7000:7000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env
    environment:
      MULTIFINANCE_MYSQL_HOST: db
      MULTIFINANCE_MYSQL_PORT: 3306
      MULTIFINANCE_MYSQL_DATABASE: ${MYSQL_DATABASE:-multifinance}
      MULTIFINANCE_MYSQL_USER: ${MYSQL_USER:-mysql_user}
      MULTIFINANCE_MYSQL_PASSWORD: ${MYSQL_PASSWORD:-mysql_password}
      MULTIFINANCE_REDIS_HOST: redis
      MULTIFINANCE_REDIS_PORT: 6379
      MULTIFINANCE_REDIS_PASSWORD: ${REDIS_PASSWORD:-password}
      MULTIFINANCE_REDIS_DB: 0
      APP_NAME: "multifinance-app-service"
      APP_PORT: 9090
      APP_GRPC_PORT: 7000
      JWT_PRIVATE_KEY: ${JWT_PRIVATE_KEY}
    networks:
      - multifinance_app_network

volumes:
  mysql_data:
  redis_data:
